name: "Rmarkdown Build"

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: R setup
      uses: r-lib/actions/setup-r@v1
    
    - name: Pandoc setup
      uses: r-lib/actions/setup-pandoc@v1
      
    - name: TinyTex setup
      uses: r-lib/actions/setup-tinytex@v1

    - name: Install Rmarkdown
      run: |
        Rscript -e 'install.packages("rmarkdown")'

    - name: Cache R packages
      uses: actions/cache@v1
      with:
        path: ${{ env.R_LIBS_USER }}
        key: R-${{ hashFiles('DESCRIPTION') }}
    
    - name: Build the document to all types
      run: |
        Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
        Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
    
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book